@startuml

' skinparam handwritten true
' skinparam monochrome true
skinparam DefaultFontName GFS Didot
skinparam packageStyle rectangle
left to right direction

title Use case diagram

actor "User" as user
actor "Server" as server

rectangle {
	usecase "Αναζήτηση" as searchLogin
	usecase "Μη έγκυρος ΑΜΚΑ." as searchLoginErrorSSN
	usecase "Μη έγκυρος ΑΦΜ." as searchLoginErrorTRN
	usecase "Είσοδος στην εφαρμογή" as searchLoginSuccess
	usecase "Αυθεντικοποίηση Χρήστη" as taxisLogin
	usecase "Αποτυχία στην Αυθεντικοποίηση του χρήστη!" as taxisLoginError
	usecase "Πληροφορίες Πολίτη" as taxisLoginSuccess

	user -- searchLogin
	user -- taxisLogin
	searchLogin -- server
	taxisLogin -- server

	searchLogin .> searchLoginSuccess : <<include>>
	searchLoginErrorSSN .> searchLogin : <<extend>>
	searchLoginErrorTRN .> searchLogin : <<extend>>
	searchLoginSuccess .> taxisLogin : <<include>>
	taxisLogin .> taxisLoginError : <<extend>>
	taxisLoginError .> taxisLogin  : <<extend>>
	taxisLogin .> taxisLoginSuccess : <<include>>
}

@enduml
